import { createCanvas } from "@napi-rs/canvas";
import { writeFileSync } from "node:fs";
import type { ScoreReport } from "../types.js";

const WIDTH = 800;
const HEIGHT = 600;
const BG = "#0f172a";
const TEXT = "#e2e8f0";
const ACCENT = "#38bdf8";
const GREEN = "#4ade80";
const GRAY = "#475569";
const BAR_BG = "#1e293b";

const DIMENSION_LABELS: Record<string, { icon: string; label: string }> = {
  brain: { icon: "🧠", label: "Brain" },
  power: { icon: "⚡", label: "Power" },
  tuning: { icon: "🎯", label: "Tuning" },
  ecosystem: { icon: "🌐", label: "Ecosystem" },
};

function drawRoundedRect(
  ctx: ReturnType<ReturnType<typeof createCanvas>["getContext"]>,
  x: number, y: number, w: number, h: number, r: number,
): void {
  ctx.beginPath();
  ctx.moveTo(x + r, y);
  ctx.lineTo(x + w - r, y);
  ctx.quadraticCurveTo(x + w, y, x + w, y + r);
  ctx.lineTo(x + w, y + h - r);
  ctx.quadraticCurveTo(x + w, y + h, x + w - r, y + h);
  ctx.lineTo(x + r, y + h);
  ctx.quadraticCurveTo(x, y + h, x, y + h - r);
  ctx.lineTo(x, y + r);
  ctx.quadraticCurveTo(x, y, x + r, y);
  ctx.closePath();
}

export function generateCard(report: ScoreReport, outputPath: string): void {
  const canvas = createCanvas(WIDTH, HEIGHT);
  const ctx = canvas.getContext("2d");

  // Background
  ctx.fillStyle = BG;
  ctx.fillRect(0, 0, WIDTH, HEIGHT);

  // Title
  ctx.fillStyle = ACCENT;
  ctx.font = "bold 20px sans-serif";
  ctx.textAlign = "center";
  ctx.fillText("⚡ AI SCORE", WIDTH / 2, 50);

  // Big score
  ctx.fillStyle = TEXT;
  ctx.font = "bold 72px sans-serif";
  ctx.fillText(`${report.total}`, WIDTH / 2, 140);

  ctx.font = "24px sans-serif";
  ctx.fillStyle = GRAY;
  ctx.fillText("/ 100", WIDTH / 2 + 60, 140);

  // Grade
  ctx.fillStyle = ACCENT;
  ctx.font = "bold 28px sans-serif";
  ctx.fillText(`${report.gradeInfo.grade} — ${report.gradeInfo.title}`, WIDTH / 2, 185);

  // Dimension bars
  const barX = 100;
  const barWidth = 400;
  const barHeight = 24;
  let barY = 230;

  for (const dim of report.dimensions) {
    const meta = DIMENSION_LABELS[dim.name] ?? { icon: "?", label: dim.name };

    ctx.fillStyle = TEXT;
    ctx.font = "16px sans-serif";
    ctx.textAlign = "left";
    ctx.fillText(`${meta.icon} ${meta.label}`, barX, barY + 17);

    // Bar background
    const bx = barX + 140;
    ctx.fillStyle = BAR_BG;
    drawRoundedRect(ctx, bx, barY, barWidth, barHeight, 4);
    ctx.fill();

    // Bar fill
    const fillWidth = Math.round((dim.score / dim.maxScore) * barWidth);
    ctx.fillStyle = GREEN;
    drawRoundedRect(ctx, bx, barY, fillWidth, barHeight, 4);
    ctx.fill();

    // Score text
    ctx.fillStyle = TEXT;
    ctx.font = "14px sans-serif";
    ctx.textAlign = "left";
    ctx.fillText(`${dim.score}/${dim.maxScore}`, bx + barWidth + 16, barY + 17);

    barY += 50;
  }

  // Footer
  ctx.fillStyle = GRAY;
  ctx.font = "14px sans-serif";
  ctx.textAlign = "center";
  ctx.fillText("Generated by ai-score", WIDTH / 2, HEIGHT - 30);

  const buffer = canvas.toBuffer("image/png");
  writeFileSync(outputPath, buffer);
}
